### ISSUE TITLE
LSPD für GTA 5

### ISSUE THREAD

**Issue by Mentanding** [ThomasMarangoni/altv-os-map-request#2]
Object + Garagen einfahrt
![sa-mp-080](https://user-images.githubusercontent.com/8605946/99195546-b6bef180-2786-11eb-9995-1a4570ee25a9.png)
![sa-mp-081](https://user-images.githubusercontent.com/8605946/99195556-bf172c80-2786-11eb-9dc8-1e9739fcc60a.png)
![sa-mp-082](https://user-images.githubusercontent.com/8605946/99195562-c50d0d80-2786-11eb-94c2-2be3cb4568cf.png)
![sa-mp-083](https://user-images.githubusercontent.com/8605946/99195566-c9392b00-2786-11eb-967f-9fd678ff583f.png)
![sa-mp-084](https://user-images.githubusercontent.com/8605946/99195570-cf2f0c00-2786-11eb-9f8f-fd62b3bffed0.png)
![sa-mp-085](https://user-images.githubusercontent.com/8605946/99195571-d3f3c000-2786-11eb-8e8e-190c77f63e4e.png)
![sa-mp-086](https://user-images.githubusercontent.com/8605946/99195573-d8b87400-2786-11eb-8947-fec4c5ab4cd9.png)

**Comment by Mentanding** [comment]
😁

**Comment by ThomasMarangoni** [comment]
You are requesting an MLO and Interior, thats not what I can do. Also you would need custom props for that.
